# Generated by Django 4.2.7 on 2024-04-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0003_aluno_votos_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='limite',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='limite',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
