# Generated by Django 4.2.7 on 2024-04-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0004_administrador_limite_aluno_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='grupo',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='aluno',
            name='grupo',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrador',
            name='limite',
            field=models.IntegerField(default=100, max_length=20),
        ),
    ]
