# Generated by Django 4.2.7 on 2024-04-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0005_administrador_grupo_aluno_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='votos',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='votos',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
