# Generated by Django 4.2.7 on 2024-04-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0007_alter_aluno_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='votos',
            field=models.IntegerField(default=0, max_length=21),
        ),
    ]
